config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  root 'posts#index'
  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  resources :relationships, only: %i[create destroy]

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_params

  def create
    @like = current_user.likes.build(post_id: params[:post_id])
    @like.save
  end
  
  def destroy
    @like = Like.find_by(post_id: @post.id, user_id: current_user.id)
    @like.destroy
  end
  
  private
  
  def set_params
    @post = Post.find(params[:post_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.already_liked?(post) %>
    <%= link_to post_like_path(post.id, current_user.id), method: :delete, remote: true, class: "like" do %>
      <i class="fa fa-heart" aria-hidden="true" style="color: rgb(255, 70, 100);"></i>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(post.id), method: :post, remote: true, class: "like" do %>
      <i class="fa fa-heart" aria-hidden="true" style="color: #C0C0C0;"></i>
    <% end %>
  <% end %>
<% else %>
  <i class="fa fa-heart" aria-hidden="true"></i>
<% end %>

<%= post.likes.length %>
<i class="fa fa-comment" aria-hidden="true"></i>
<%= post.comments.length %>

app/views/likes/create.js.erb
$('.like-<%= @post.id %>').html("<%= j(render 'likes/like', post: @post) %>");

app/views/likes/destroy.js.erb
$('.like-<%= @post.id %>').html("<%= j(render 'likes/like', post: @post) %>");