config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  root 'posts#index'
  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  resources :relationships, only: %i[create destroy]

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  #バリデーション
  validates :title, presence: true, length: { maximum: 20 }

  mount_uploader :image, PostImageUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :current_user_authenticate, only: %i[edit update destroy]

  def index
    all_index
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path, notice: '投稿しました！'
    else
      render :new
    end
  end

  def destroy
    @post.destroy if @post.user_id == current_user.id
    redirect_to root_path, notice: '削除しました。'
  end

  def edit
  end

  def update
    @post.update(post_params)
    if @post.save
      redirect_to user_path(@post.user.id), notice: '編集しました'
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @like = Like.new
    @post_comments = @post.comments.includes(:user).order('created_at DESC')
  end

  def show_posts
    @user = current_user
    @posts = Post.where(user_id: @user.id).all.order("created_at DESC").page(params[:page]).per(20)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :image)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def current_user_authenticate
    @post = Post.find(params[:id])
    redirect_to root_path, alert: '権限がありません' if @post.user.id != current_user.id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_area.html.erb
<% if user_signed_in? %>
  <%= form_with model: [@post, @comment], local: true do |f| %>
    <div>
      <div>
        <h5>コメントする</h4>
        <%= f.text_area :content, placeholder: "コメントを入力", class: "p-2 mt-1 rounded" %>
      </div>
      <div>
        <%= f.submit "コメント", class: "btn btn-primary mt-3" %>
      </div>
    </div>
  <% end %>
<% end %>

<% unless @post_comments.present? %>
  <div class="message mt-4">
    この投稿へのコメントはありません
  </div>
<% end %>

<div id='messages'>
  <% @post_comments.each do |comment| %>
    <div class="message mt-3">
      <%= comment.content.truncate(100) %>
      <br>

      <div class="mt-2">
        <span class="post-time-message"><%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span>

          <% if comment.user.image? %>
            <%= link_to image_tag(comment.user.image.thumb.url, class:"user-icon"), user_path(comment.user) %>
          <% else %>
            <%= link_to image_tag("default_thumb.jpg", class:"user-icon"), user_path(comment.user) %>
          <% end %>

        <% if comment.user == current_user %>
            <%= link_to "あなた", comment.user, class: "link message-user" %> |
            <%= link_to "削除", post_comment_path(comment.post_id, comment.id), method: :delete, data: { confirm: "本当に削除しますか？" } %>
        <% else %>
            <%= link_to comment.user.name, comment.user, class: "link message-user" %>
            <span class="message-user-san"></span>さん
        <% end %>
      </div>

    </div>
  <% end %>
</div>

app/views/posts/_posts_form.html.erb
<%= form_with model: @post, local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, autofocus: true, placeholder: "20文字まで", class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :content, "本文" %>
    <%= f.text_area :content, placeholder: "本文を入力してください。", rows: '6', class: "form-control" %>
  </div>

  <%= f.label :画像 %>
  <%= f.file_field :image, class: "image" %>
  
  <div class="submit">
    <%= f.submit post_save, class: 'btn btn-primary btn-block' %>
  </div>
<% end %>
  
<br/>
<div>
  <%= link_to :back do %>
    <button class="btn btn-secondary btn-block">戻る</button>
  <% end %>
</div>

app/views/posts/create.html.erb
<div class="contents row">
  <div class="success">
    <h2>投稿が完了しました。</h2>
    <%= link_to '投稿一覧へ戻る', posts_path, {class: 'btn btn-primary withripple' } %>
  </div>
</div>

app/views/posts/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h2>削除が完了しました。</h2>
    <%= link_to '投稿一覧へ戻る', posts_path, { class: 'btn btn-primary withripple' } %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="contents mw-md">
 <h2>投稿を編集する</h2>

 <%= render 'posts/posts_form', post_save: "変更を保存" %>
</div>

app/views/posts/index.html.erb
<div class="top_container">
  <h1>Touringood</h1>
  <p>ツーリングのルート共有アプリです。</p>
  
  <div class="sign_up">
  <% if user_signed_in? %>
    <%= link_to "投稿する", new_post_path, class: 'btn btn-primary' %>
  <%else%>
    <%= link_to "新規登録", new_user_registration_path, class: 'btn btn-primary' %>
  <% end %>
  </div>
</div>

<%= render 'shared/users_posts', posts: @posts %>

app/views/posts/new.html.erb
<div class="contents mw-md">
  <h2>投稿する</h2>
  <%= render 'posts/posts_form', post_save: "投稿する" %>
</div>

app/views/posts/show.html.erb
<div class="post-show-container">
  <h1><%= @post.title %></h1>
  <div>
    <% if @post.image? %>
    <%= image_tag @post.image.url, class: "post-show-image" %>
    <% end %>

    <%= @post.content %><br/>
    <%= @post.created_at.strftime("%Y-%m-%d %H:%M:%S") %> | 

    <% if @post.user_id == current_user&.id %>
        <%= link_to "編集", edit_post_path(@post.id) %> | 
        <%= link_to "削除", post_path(@post.id), method: :delete, data: { confirm: "本当に削除しますか？" } %>
    <% end %>

    <span class="like-<%= @post.id %> mr-auto">
      <%= render 'likes/like', post: @post %>
    </span>
    <% if @post.user.image? %>
      <%= link_to image_tag(@post.user.image.thumb.url, class:"user-icon"), user_path(@post.user) %>
    <% else %>
      <%= link_to image_tag("default_thumb.jpg", class:"user-icon"), user_path(@post.user) %>
    <% end %>

    <%= link_to @post.user.name, user_path(@post.user) %>
  </div>

  <%= render 'posts/comment_area' %>
</div>