config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  root 'posts#index'
  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
  end
  resources :relationships, only: %i[create destroy]

end

app/views/layouts/_error_messages.html.erb
<%# エラー時はエラーメッセージ作成 %>
<% if model.errors.any? %>
<div>
   <% model.errors.full_messages.each do |message| %>
   <div class="alert alert-danger">
   <%= message %>
   </div>
   <% end %>
</div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %> alert-dismissible" role="alert" id="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">close</span>
    </button>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <div class="top_link">
      <%= link_to "Trouringood", root_path, class: 'btn' %>
    </div>
      <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
    <div class="account_menu">
      <% if user_signed_in? %> 
          <p><strong><%= current_user.name %></strong></p>
          <div class="dropdown">
            <button class="btn " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.image? %>
                <%= image_tag(current_user.image.thumb.url, class:"user-icon") %>
              <% else %>
                <%= image_tag("default30.jpg", class:"user-icon") %>
              <% end %>
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
              <%= link_to 'マイページ', user_path(current_user), class: 'dropdown-item' %>
              <%= link_to '設定', edit_user_registration_path, class: 'dropdown-item' %>
              <%= link_to "ログアウト", sign_out_path, class: 'dropdown-item' %>
            </div>
          </div>
      <% else %>
          <%= link_to "新規登録", new_user_registration_path, class: 'btn btn-outline-light btn-sm' %>
          <%= link_to "ログイン", new_user_session_path, class: 'btn btn-outline-light btn-sm' %>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <title>Touringood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="<%= branch_layout %>">
      <%= render 'layouts/flash_messages' unless devise_controller? %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>